### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by ghost** [Viliami/Casio-FakeOS#2]
I know this isn't really the right place to ask, but I found your program through a forum and would love to use it but you filedropper.com link is down and I don't know how to use these files. :camel: 

Could you maybe reupload your program? :)

Thanks!

**Comment by Viliami** [comment]
Hello Joe,
I have just added the .G1A file to the repository.
Just copy the "FAKEOS.G1A" file to your calculator using the FA-124 program and it should work.
